"""
Global config for all scripts.
"""

# ---------- Imports ---------- #
import matplotlib as plt

# ---------- Paths ---------- #
"""Define paths for orignal data, preprocessed data, and output path for plots."""

data_root_path = "/ceph/e4/users/cdelitzsch/public/forClusterStudies/"
data_save_path = "/ceph/e4/users/bschuchardt/public/MA/data/"
output_path = "/ceph/e4/users/bschuchardt/public/MA/TopoClassifier/output"

# ---------- Feature Columns ---------- #
columns = [
    "clusterE",
    "clusterPt",
    "cluster_FIRST_ENG_DENS",
    "cluster_EM_PROBABILITY",
    "cluster_CENTER_LAMBDA",
    "cluster_CENTER_MAG",
    "cluster_nCells_tot",
    "cluster_ENG_FRAC_EM",
    "cluster_SECOND_TIME",
    "cluster_AVG_TILE_Q",
    "cluster_AVG_LAR_Q",
    "cluster_SECOND_R",
    "cluster_LATERAL",
    "cluster_time",
    "cluster_ISOLATION",
    "cluster_DELTA_ALPHA",
    "cluster_DELTA_THETA",
    "clusterEta",
    "cluster_DELTA_PHI",
    "clusterPhi",
    "cluster_SECOND_LAMBDA",
    "cluster_LONGITUDINAL",
    "cluster_CELL_SIGNIFICANCE",
    "cluster_ENG_CALIB_TOT",
    "cluster_SIGNIFICANCE",
    "nPrimVtx",
    "avgMu",
    "jetCnt",
    "eventNumber",
    "jetRawEta",
    "jetRawPhi",
    "jetRawE",
    "jetRawPt",
]

log_features = [
    "clusterE",
    "clusterPt",
    "cluster_FIRST_ENG_DENS",
    "cluster_CENTER_LAMBDA",
    "cluster_nCells_tot",
    "cluster_SECOND_TIME",
    "cluster_AVG_TILE_Q",
    "cluster_AVG_LAR_Q",
    "cluster_SECOND_R",
    "cluster_DELTA_ALPHA",
    "cluster_SECOND_LAMBDA",
    "cluster_CELL_SIGNIFICANCE",
    "jetRawE",
    "jetRawPt",
]

normal_features = [
    "clusterE",
    "cluster_FIRST_ENG_DENS",
    "cluster_EM_PROBABILITY",
    "cluster_CENTER_LAMBDA",
    "cluster_CENTER_MAG",
    "cluster_nCells_tot",
    "cluster_ENG_FRAC_EM",
    "cluster_SECOND_TIME",
    "cluster_AVG_TILE_Q",
    "cluster_AVG_LAR_Q",
    "cluster_LATERAL",
    "cluster_ISOLATION",
    "cluster_DELTA_THETA",
    "clusterEta",
    "cluster_DELTA_PHI",
    "clusterPhi",
    "cluster_LONGITUDINAL",
    "jetRawEta",
    "jetRawPhi",
    "nPrimVtx",
    "avgMu",
]

cluster_features = [
    "clusterE",
    "clusterPt",
    "cluster_FIRST_ENG_DENS",
    "cluster_EM_PROBABILITY",
    "cluster_CENTER_LAMBDA",
    "cluster_CENTER_MAG",
    "cluster_nCells_tot",
    "cluster_ENG_FRAC_EM",
    "cluster_SECOND_TIME",
    "cluster_AVG_TILE_Q",
    "cluster_AVG_LAR_Q",
    "cluster_SECOND_R",
    "cluster_LATERAL",
    "cluster_time",
    "cluster_ISOLATION",
    "cluster_DELTA_ALPHA",
    "cluster_DELTA_THETA",
    "clusterEta",
    "cluster_DELTA_PHI",
    "clusterPhi",
    "cluster_SECOND_LAMBDA",
    "cluster_LONGITUDINAL",
    "cluster_CELL_SIGNIFICANCE",
    "cluster_ENG_CALIB_TOT",
    "cluster_SIGNIFICANCE",
]

feature_keys = [
    "clusterE",
    "cluster_FIRST_ENG_DENS",
    "cluster_EM_PROBABILITY",
    "cluster_CENTER_LAMBDA",
    "cluster_CENTER_MAG",
    "cluster_nCells_tot",
    "cluster_ENG_FRAC_EM",
    "cluster_SECOND_TIME",
    "cluster_AVG_TILE_Q",
    "cluster_AVG_LAR_Q",
    "cluster_SECOND_R",
    "cluster_LATERAL",
    "cluster_time",
    "cluster_ISOLATION",
]

jet_feature_keys = [
    "clusterE",
    "cluster_FIRST_ENG_DENS",
    "cluster_EM_PROBABILITY",
    "cluster_CENTER_LAMBDA",
    "cluster_CENTER_MAG",
    "cluster_nCells_tot",
    "cluster_ENG_FRAC_EM",
    "cluster_SECOND_TIME",
    "cluster_AVG_TILE_Q",
    "cluster_AVG_LAR_Q",
    "cluster_SECOND_R",
    "cluster_LATERAL",
    "cluster_time",
    "cluster_ISOLATION",
    "jetRawE",
    "diffEta",
    "zT",
    "zL",
    "zRel",
]


# ---------- Plot Configuration ---------- #
def set_style():
    plt.rcParams.update(
        {
            "figure.figsize": (7.2, 4.8),
            "figure.constrained_layout.use": True,
            "savefig.bbox": "tight",
            "text.usetex": True,
            "axes.prop_cycle": plt.cycler(
                color=[
                    "#0072B2",  # Blue
                    "#D55E00",  # Vermilion
                    "#009E73",  # Bluish green
                    "#E69F00",  # Orange
                    "#56B4E9",  # Sky blue
                    "#F0E442",  # Yellow
                    "#CC79A7",  # Reddish purple
                    "#000000",  # Black
                ]
            ),
            "lines.linewidth": 1.8,
            "lines.markersize": 5,
            "legend.frameon": False,
            "legend.fontsize": 11,
            "font.size": 12,
            "text.usetex": True,
        }
    )


latex_labels = {
    "clusterE": r"$E_{\mathrm{clus}}^{\mathrm{EM}}$",
    "clusterPt": r"$p_{\mathrm{T}}^{\mathrm{clus}}$",
    "cluster_FIRST_ENG_DENS": r"$\langle \rho_{\mathrm{cell}} \rangle$",
    "cluster_EM_PROBABILITY": r"$\mathcal{P}_{\mathrm{clus}}^{\mathrm{EM}}$",
    "cluster_CENTER_LAMBDA": r"$\lambda_{\mathrm{clus}}$",
    "cluster_CENTER_MAG": r"$c$",
    "cluster_nCells_tot": r"$n_{\mathrm{cells}}$",
    "cluster_ENG_FRAC_EM": r"$f_{\mathrm{emc}}$",
    "cluster_SECOND_TIME": r"$\sigma_{\mathrm{t}}^{2}$",
    "cluster_AVG_TILE_Q": r"$\langle Q_{\mathrm{Tile}} \rangle$",
    "cluster_AVG_LAR_Q": r"$\langle Q_{\mathrm{LAr}} \rangle$",
    "cluster_SECOND_R": r"$\langle r_{\mathrm{cell}}^{2} \rangle$",
    "cluster_LATERAL": r"$m_{\mathrm{lat}}^{2}$",
    "cluster_time": r"$t_{\mathrm{clus}}$",
    "cluster_ISOLATION": r"$f_{\mathrm{iso}}$",
    "cluster_DELTA_ALPHA": r"$\Delta \alpha$",
    "cluster_DELTA_THETA": r"$\Delta \theta$",
    "clusterEta": r"$y_{\mathrm{clus}}$",
    "cluster_DELTA_PHI": r"$\Delta \phi$",
    "clusterPhi": r"$\phi_{\mathrm{clus}}$",
    "cluster_SECOND_LAMBDA": r"$\langle \lambda_{\mathrm{cell}}^{2} \rangle$",
    "cluster_LONGITUDINAL": r"$m_{\mathrm{long}}^{2}$",
    "cluster_CELL_SIGNIFICANCE": r"$\max \{ \zeta_{\mathrm{clus}}^{\mathrm{EM}} \}$",
    "cluster_ENG_CALIB_TOT": r"$E_{\mathrm{clus}}^{\mathrm{dep}}$",
    "cluster_SIGNIFICANCE": r"$\varsigma_{\mathrm{clus}}^{\mathrm{EM}}$",
    "nPrimVtx": r"$n_{\mathrm{PV}}$",
    "avgMu": r"$\langle \mu \rangle$",
    "jetRawEta": r"$\eta_{\mathrm{jet}}$",
    "jetRawPhi": r"$\phi_{\mathrm{jet}}$",
    "jetRawE": r"$E_{\mathrm{jet}}^{\mathrm{const}}$",
    "jetRawPt": r"$p_{\mathrm{T}}^{\mathrm{jet}}$",
    "diffEta": r"$\Delta \eta$",
    "zT": r"$z_{\mathrm{T}}$",
    "zL": r"$z_{\mathrm{L}}$",
    "zRel": r"$z_{\mathrm{rel}}$",
}

plot_settings = {
    "avgMu": {
        "feature": "avgMu",
        "integer_bins": True,
        "nbins": 40,
        "start": 0,
        "stop": 100,
        "xlabel": r"$\langle \mu \rangle$",
        "ylabel": "Number of topoclusters",
        "logx": False,
    },
    "NPV": {
        "feature": "nPrimVtx",
        "integer_bins": True,
        "nbins": 50,
        "start": 0,
        "stop": 50,
        "xlabel": r"$N_{\mathrm{PV}}$",
        "ylabel": "Number of topoclusters",
        "logx": False,
    },
    "clusterE": {
        "feature": "clusterE",
        "integer_bins": False,
        "nbins": 50,
        "start": 1e-1,
        "stop": 1e2,
        "xlabel": r"$E_{\mathrm{clus}}^{\mathrm{EM}} [\mathrm{GeV}]$",
        "logx": True,
    },
    "cluster_FIRST_ENG_DENS": {
        "feature": "cluster_FIRST_ENG_DENS",
        "integer_bins": False,
        "nbins": 100,
        "start": 1e-10,
        "stop": 1e-4,
        "xlabel": r"$\langle \rho_{\mathrm{cell}} \rangle [\mathrm{GeV}/\mathrm{mm}^{3}]$",
        "logx": True,
    },
    "cluster_EM_PROBABILITY": {
        "feature": "cluster_EM_PROBABILITY",
        "integer_bins": False,
        "nbins": 50,
        "start": 0,
        "stop": 1,
        "xlabel": r"$\mathcal{P}_{\mathrm{clus}}^{\mathrm{EM}}$",
    },
    "cluster_CENTER_LAMBDA": {
        "feature": "cluster_CENTER_LAMBDA",
        "integer_bins": False,
        "nbins": 50,
        "start": 1e0,
        "stop": 1e4,
        "xlabel": r"$\lambda_{\mathrm{clus}} [\mathrm{mm}]$",
        "logx": True,
    },
    "cluster_nCells_tot": {
        "feature": "cluster_nCells_tot",
        "integer_bins": False,
        "nbins": 50,
        "start": 1e1,
        "stop": 1e3,
        "xlabel": r"$n_{\mathrm{cells}}$",
        "logx": True,
    },
    "cluster_CENTER_MAG": {
        "feature": "cluster_CENTER_MAG",
        "integer_bins": False,
        "nbins": 50,
        "start": 1000,
        "stop": 7000,
        "xlabel": r"$c [\mathrm{mm}]$",
    },
    "cluster_ENG_FRAC_EM": {
        "feature": "cluster_ENG_FRAC_EM",
        "integer_bins": False,
        "nbins": 50,
        "start": 0,
        "stop": 1,
        "xlabel": r"$f_{\mathrm{emc}}$",
    },
    "cluster_SECOND_TIME": {
        "feature": "cluster_SECOND_TIME",
        "integer_bins": False,
        "nbins": 50,
        "start": 1e-10,
        "stop": 1e-5,
        "xlabel": r"$\sigma_{\mathrm{t}}^{2} [\mathrm{ns}^2]$",
        "logx": True,
    },
    "cluster_AVG_TILE_Q": {
        "feature": "cluster_AVG_TILE_Q",
        "integer_bins": False,
        "nbins": 50,
        "start": 0,
        "stop": 100,
        "xlabel": r"$\langle Q_{\mathrm{Tile}} \rangle [$ADC counts$]$",
        "logx": False,
        "logy": True,
    },
    "cluster_AVG_LAR_Q": {
        "feature": "cluster_AVG_LAR_Q",
        "integer_bins": False,
        "nbins": 1000,
        "start": 0,
        "stop": 4000,
        "xlabel": r"$\langle Q_{\mathrm{LAr}} \rangle [$ADC counts$]$",
        "logx": False,
        "logy": True,
    },
    "cluster_SECOND_R": {
        "feature": "cluster_SECOND_R",
        "integer_bins": False,
        "nbins": 50,
        "start": 1e-6,
        "stop": 1e-3,
        "xlabel": r"$\langle r_{\mathrm{cell}}^{2} \rangle [\mathrm{mm}^2]$",
        "logx": True,
    },
    "cluster_LATERAL": {
        "feature": "cluster_LATERAL",
        "integer_bins": False,
        "nbins": 50,
        "start": 0,
        "stop": 1,
        "xlabel": r"$\langle m_{\mathrm{lateral}}^{2} \rangle$",
    },
    "cluster_time": {
        "feature": "cluster_time",
        "integer_bins": False,
        "nbins": 100,
        "start": -50,
        "stop": 50,
        "xlabel": r"$t_{\mathrm{clus}} [\mathrm{ns}]$",
    },
    "cluster_ISOLATION": {
        "feature": "cluster_ISOLATION",
        "integer_bins": False,
        "nbins": 50,
        "start": 0,
        "stop": 1,
        "xlabel": r"$f_{\mathrm{iso}}$",
    },
    "cluster_DELTA_ALPHA": {
        "feature": "cluster_DELTA_ALPHA",
        "integer_bins": False,
        "nbins": 50,
        "start": 0,
        "stop": 1,
        "xlabel": r"$\Delta \alpha [\mathrm{rad}]$",
    },
    "cluster_DELTA_THETA": {
        "feature": "cluster_DELTA_THETA",
        "integer_bins": False,
        "nbins": 50,
        "start": -1,
        "stop": 1,
        "xlabel": r"$\Delta \theta [\mathrm{rad}]$",
    },
    "clusterEta": {
        "feature": "clusterEta",
        "integer_bins": False,
        "nbins": 50,
        "start": -3.5,
        "stop": 3.5,
        "xlabel": r"$y_{\mathrm{clus}}$",
    },
    "clusterPhi": {
        "feature": "clusterPhi",
        "integer_bins": False,
        "nbins": 50,
        "start": -3.5,
        "stop": 3.5,
        "xlabel": r"$\phi_{\mathrm{clus}}$ ",
    },
    "cluster_SECOND_LAMBDA": {
        "feature": "cluster_SECOND_LAMBDA",
        "integer_bins": False,
        "nbins": 50,
        "start": 1,
        "stop": 1e6,
        "xlabel": r"$\langle \lambda_{\mathrm{cell}}^{2} \rangle [\mathrm{mm}^2]$",
        "logx": True,
    },
    "cluster_LONGITUDINAL": {
        "feature": "cluster_LONGITUDINAL",
        "integer_bins": False,
        "nbins": 50,
        "start": 0,
        "stop": 1,
        "xlabel": r"$m_{\mathrm{long}}^{2}$ ",
    },
    "cluster_CELL_SIGNIFICANCE": {
        "feature": "cluster_CELL_SIGNIFICANCE",
        "integer_bins": False,
        "nbins": 50,
        "start": 1,
        "stop": 1e3,
        "xlabel": r"$max\{\varsigma_{\mathrm{clus}}^{\mathrm{EM}}\}$",
        "logx": True,
    },
}
